name: "book-store-app"
services:
    books-service:
        image: ansbeno/bookstore-books-service
        container_name: books-service
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - DB_URL=jdbc:postgresql://books-db:5432/postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            # - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/books
            # - MANAGEMENT_TRACING_ENABLED=true
            # - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
        ports:
            - "8081:8081"
        restart: unless-stopped
        depends_on:
            books-db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 700m

    order-service:
        image: ansbeno/bookstore-order-service
        container_name: order-service
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            # - ORDERS_BOOK_SERVICE_URL=http://api-gateway:8989/catalog
            - BOOKS_SERVICE_URL=http://books-service:8081
            - DB_URL=jdbc:postgresql://orders-db:5432/postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - RABBITMQ_HOST=bookstore-rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - OAUTH2_SERVER_URL=http://keycloak:9191
            - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/orders
            - MANAGEMENT_TRACING_ENABLED=true
            - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
        ports:
            - "8082:8082"
        restart: unless-stopped
        depends_on:
            orders-db:
                condition: service_healthy
            bookstore-rabbitmq:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 700m
        labels:
            logging: "promtail"
